name: Erlang CT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    strategy:
      matrix:
        otp: ['27.0']
        rebar3: ['3.24.0']
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - uses: actions/checkout@v4
      - name: Compiling
        run: |
          rebar3 compile
      - name: Run ct
        run: |
          rebar3 ct
      - name: Run Dialyzer
        run: |
          rebar3 dialyzer
